#!/usr/bin/env python3

"""
Create flashcards from Jones textbook CSVs.

Inputs:
  - CSV files from:
      textbook-jones-exercises.csv
      textbook-jones-vocabulary.csv
  - JSON files (stubbed - not implemented yet)

Outputs (choose via --format):
  - anki (default): builds an .apkg using genanki with multiple note types
  - two_col_csv: emits a simple two-column CSV (Front,Back)

Model definitions are loaded at runtime from YAML files in the project root:
  - genanki-model-exercise.yml
  - genanki-model-noun.yml
  - genanki-model-verb.yml
  - genanki-model-demonstrative.yml
  - genanki-model-particle.yml
  - genanki-model-idiom.yml
  - genanki-model-other.yml (fallback)

Rules implemented from the requirements:
  - Include all CSV columns as note fields except `Ex/Voc` and `Note/Warning`.
  - Separate note types for Exercises and POS (noun/verb/demonstrative/particle/idiom/other) in Vocabulary.
  - Noun/verb create up to three card templates (singular/dual/plural or perfect/imperfect/verbal noun).
    If the front field is empty, that card will not be generated by Anki.
  - Exercises: front shows Arabic; back shows all fields except Anki_ID.
  - Vocabulary backs show all fields and include a compact table for the three Arabic forms.
  - Card GUIDs come strictly from `Anki_ID`.
  - Stub function for Quran audio download; media insertion is left commented out per instructions.
"""

import argparse
import csv
import os
import re
import sys
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover
    yaml = None

try:
    import genanki  # type: ignore
except ImportError:  # pragma: no cover
    genanki = None


# ----------------------------
# Data structures
# ----------------------------


@dataclass
class ExerciseRow:
    anki_id: str
    page_number: str
    lesson_number: str
    exercise_number: str
    arabic_text: str
    transliteration: str
    english_text: str
    quran_surah: str
    quran_ayah: str
    usage_notes: str


@dataclass
class VocabRow:
    anki_id: str
    page_number: str
    lesson_number: str
    arabic_word_singular: str
    arabic_word_dual: str
    arabic_word_plural: str
    english_translation: str
    verb_form: str
    part_of_speech: str
    triliteral_root: str
    usage_notes: str


# ----------------------------
# Utility functions
# ----------------------------


def _get_script_dir() -> str:
    """Return the directory where this script is located."""
    return os.path.dirname(os.path.abspath(__file__))


def _read_csv(path: str) -> Tuple[List[str], List[Dict[str, str]]]:
    """Read a CSV file and return headers and rows as a list of dicts."""
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = [dict(r) for r in reader]
        headers = reader.fieldnames or []
    return headers, rows


def _is_exercise(headers: List[str]) -> bool:
    """Check if CSV headers indicate an exercise file."""
    required_exercise_headers = {
        "Exercise Number",
        "Arabic Text",
        "Quran Chapter/Surah",
        "Quran Verse/Ayah",
    }
    return required_exercise_headers.issubset(set(headers))


def _is_vocab(headers: List[str]) -> bool:
    """Check if CSV headers indicate a vocabulary file."""
    required_vocab_headers = {
        "Sing. / Perf.",
        "Dual / Imperf.",
        "Plural / Verbal N.",
        "English Translations",
    }
    return required_vocab_headers.issubset(set(headers))


def _pad_anki_id_parts(anki_id: str) -> str:
    """Pad parts of Anki_ID with leading zeros if needed."""
    anki_id_parts = anki_id.split("-")
    if len(anki_id_parts[0]) == 1:
        anki_id_parts[0] = anki_id_parts[0].zfill(2)
    elif len(anki_id_parts[0]) > 2:
        sys.stderr.write(
            "Warning: Anki_ID first part longer than 2 digits, unexpected format. Sort will not work well\n"
        )

    if len(anki_id_parts[2]) == 1:
        anki_id_parts[2] = anki_id_parts[2].zfill(2)
    elif len(anki_id_parts[2]) > 2:
        sys.stderr.write(
            "Warning: Anki_ID third part longer than 2 digits, unexpected format. Sort will not work well\n"
        )

    return "-".join(anki_id_parts)


def _map_exercise_row(row: Dict[str, str]) -> ExerciseRow:
    """Map a CSV row dict to ExerciseRow dataclass."""

    # Pad anki_id with leading zeros if needed
    anki_id = _pad_anki_id_parts(row.get("Anki_ID") or "")

    return ExerciseRow(
        anki_id,
        page_number=(row.get("Page Number") or "").strip(),
        lesson_number=(row.get("Lesson Number") or "").strip(),
        exercise_number=(row.get("Exercise Number") or "").strip(),
        arabic_text=(row.get("Arabic Text") or "").strip(),
        transliteration=(row.get("Transliteration") or "").strip(),
        english_text=(row.get("English Text") or "").strip(),
        quran_surah=(row.get("Quran Chapter/Surah") or "").strip(),
        quran_ayah=(row.get("Quran Verse/Ayah") or "").strip(),
        usage_notes=(row.get("Usage Notes etc") or "").strip(),
    )


def _map_vocab_row(row: Dict[str, str]) -> VocabRow:
    """Map a CSV row dict to VocabRow dataclass."""

    # Pad anki_id with leading zeros if needed
    anki_id = _pad_anki_id_parts(row.get("Anki_ID") or "")

    return VocabRow(
        anki_id,
        page_number=(row.get("Page Number") or "").strip(),
        lesson_number=(row.get("Lesson Number") or "").strip(),
        arabic_word_singular=(row.get("Sing. / Perf.") or "").strip(),
        arabic_word_dual=(row.get("Dual / Imperf.") or "").strip(),
        arabic_word_plural=(row.get("Plural / Verbal N.") or "").strip(),
        english_translation=(row.get("English Translations") or "").strip(),
        verb_form=(row.get("Verb Form") or "").strip(),
        part_of_speech=(row.get("Part of Speech") or "").strip(),
        triliteral_root=(row.get("Triliteral Root") or "").strip(),
        usage_notes=(row.get("Usage Notes etc") or "").strip(),
    )


def _load_yaml_file(filename: str) -> Optional[Dict]:
    """Load a YAML model definition file from the script directory."""

    if yaml is None:
        return None

    script_dir = _get_script_dir()
    path = os.path.join(script_dir, filename)

    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _make_model_from_yaml(model_dict: Dict) -> "genanki.Model":
    """Create a genanki.Model from a loaded YAML dict."""
    return genanki.Model(
        model_id=int(model_dict["model_id"]),
        name=model_dict["name"],
        fields=model_dict["fields"],
        templates=model_dict["templates"],
        css=model_dict.get("css", ""),
    )


def _normalize_pos(pos: str) -> str:
    """Normalize Part of Speech to a canonical key for model lookup."""

    pos_lower = (pos or "").strip().lower()

    if pos_lower == "verb":
        return "verb"
    if pos_lower == "noun":
        return "noun"
    if "demonstrative" in pos_lower:
        return "demonstrative"
    if "idiom" in pos_lower:
        return "idiom"
    if any(
        kw in pos_lower for kw in ["particle", "interrogative", "conjunction", "adverb"]
    ):
        return "particle"
    return "other"


def _get_vocab_model_filename(pos_key: str) -> str:
    """Get the YAML filename for a normalized POS key."""

    mapping = {
        "verb": "genanki-model-verb.yml",
        "noun": "genanki-model-noun.yml",
        "demonstrative": "genanki-model-demonstrative.yml",
        "particle": "genanki-model-particle.yml",
        "idiom": "genanki-model-idiom.yml",
        "other": "genanki-model-other.yml",
    }
    return mapping.get(pos_key, "genanki-model-other.yml")


def _ensure_genanki_available():
    """Exit with error if genanki is not installed."""
    if genanki is None:
        sys.stderr.write("ERROR: genanki is not installed. Please run:\n")
        sys.stderr.write("  pip install genanki pyyaml\n")
        sys.exit(2)


def _ensure_yaml_available():
    """Exit with error if pyyaml is not installed."""
    if yaml is None:
        sys.stderr.write("ERROR: pyyaml is not installed. Please run:\n")
        sys.stderr.write("  pip install pyyaml\n")
        sys.exit(2)


# ----------------------------
# Audio (stub) - TODO
# ----------------------------


def parse_quran_reference(surah: str, ayah: str) -> Optional[Tuple[int, int]]:
    """
    Parse Quran surah and ayah numbers from strings.
    Returns (surah_num, ayah_num) or None if parsing fails.
    """

    try:
        surah_num = int(surah.strip())
        ayah_num = int(ayah.strip())
        if 1 <= surah_num <= 114 and ayah_num >= 1:
            return surah_num, ayah_num
    except (ValueError, AttributeError):
        pass
    return None


def download_quran_audio_stub(surah: str, ayah: str) -> Optional[str]:
    """
    TODO: Implement audio download for Quran Surah/Ayah.
    Return a local filename of the downloaded audio or None on failure.

    Example implementation approach:
    1. Parse surah/ayah numbers
    2. Download from EveryAyah.com or Quran.com API
    3. Save to local file like: quran_audio/001_001.mp3
    4. Return the filename for media inclusion

    Example API URLs:
    - EveryAyah: https://everyayah.com/data/Alafasy_128kbps/001001.mp3
    - Format: {surah:03d}{ayah:03d}.mp3
    """

    ref = parse_quran_reference(surah, ayah)
    if ref is None:
        return None

    surah_num, ayah_num = ref

    # TODO: Uncomment rando audio site and test. Implement?
    # import urllib.request
    #
    # # Create audio directory if needed
    # audio_dir = _get_script_dir() / "quran_audio"
    # audio_dir.mkdir(exist_ok=True)
    #
    # # Format filename
    # filename = f"{surah_num:03d}{ayah_num:03d}.mp3"
    # local_path = audio_dir / filename
    #
    # # Skip if already downloaded
    # if local_path.exists():
    #     return str(local_path)
    #
    # # Download from EveryAyah (Alafasy recitation)
    # url = f"https://everyayah.com/data/Alafasy_128kbps/{filename}"
    # try:
    #     urllib.request.urlretrieve(url, local_path)
    #     return str(local_path)
    # except Exception as e:
    #     sys.stderr.write(f"Warning: Failed to download audio for {surah}:{ayah}: {e}\n")
    #     return None

    return None


def _get_audio_tag(audio_file: Optional[str]) -> str:
    """
    Generate Anki audio tag for a media file.
    Returns empty string if no audio file.
    """

    if audio_file:
        filename = os.path.basename(audio_file)
        return f"[sound:{filename}]"
    return ""


# ----------------------------
# Anki building
# ----------------------------


def _build_exercise_note_model() -> Optional["genanki.Model"]:
    """Build the exercise note model from YAML."""

    model = _load_yaml_file("genanki-model-exercise.yml")
    if model and genanki:
        return _make_model_from_yaml(model)
    return None


def _build_vocab_note_model_for(pos: str) -> Optional["genanki.Model"]:
    """Build a vocabulary note model for the given POS from YAML."""

    pos_key = _normalize_pos(pos)
    fname = _get_vocab_model_filename(pos_key)
    model = _load_yaml_file(fname)
    if model and genanki:
        return _make_model_from_yaml(model)
    return None


def _exercise_note_fields(er: ExerciseRow) -> List[str]:
    """
    Return field values for an exercise note.
    Order must match genanki-model-exercise.yml fields.
    """
    return [
        er.anki_id,
        er.page_number,
        er.lesson_number,
        er.exercise_number,
        er.arabic_text,
        er.transliteration,
        er.english_text,
        er.quran_surah,
        er.quran_ayah,
        er.usage_notes,
    ]


def _vocab_note_fields(vr: VocabRow) -> List[str]:
    """
    Return field values for a vocabulary note.
    Order must match the vocab YAML fields.
    """

    # TODO better way to map this?
    return [
        vr.anki_id,
        vr.page_number,
        vr.lesson_number,
        vr.arabic_word_singular,
        vr.arabic_word_dual,
        vr.arabic_word_plural,
        vr.english_translation,
        vr.verb_form,
        vr.part_of_speech,
        vr.triliteral_root,
        vr.usage_notes,
    ]


def _sanitize_tag(s: str) -> str:
    """Sanitize a string for use as an Anki tag."""
    # Replace spaces and special chars with underscores
    return re.sub(r"[^\w-]", "_", s.strip().lower())


def subdeck_create_or_get(
    subdecks_dict: Dict[str, "genanki.Deck"],
    lesson_key: str,
    root_deck_name: str,
    subdeck_type: str,
    created_subdecks: bool,
) -> tuple["genanki.Deck", bool]:
    """Get or create a subdeck for the given lesson key."""

    if lesson_key in subdecks_dict:
        # don't change the value of created_subdecks here,
        # if already True keep as True, even though no deck created *here*,
        # we want to know if any deck was created in the whole process
        return subdecks_dict[lesson_key], created_subdecks
    else:
        import random

        # TODO hardcoded right now to ensure a not less than 2 character long Lesson key...
        #  but that is an assumption from the textbook's chapter numbering. will break with other keys.
        #  or at least not sort well
        # the `::` tells Anki that the following string is the subdeck name for the root deck whose name is before the `::`
        subdeck_name = (
            f"{root_deck_name}::Lesson {lesson_key.zfill(2)} - {subdeck_type}"
        )
        subdeck = genanki.Deck(
            deck_id=random.randrange(1 << 30, 1 << 31),
            name=subdeck_name,
        )

        # add the newly created subdeck to the dict
        subdecks_dict[lesson_key] = subdeck
        created_subdecks = True

        return subdeck, created_subdecks


def _add_anki_notes(
    deck: "genanki.Deck",
    media: List[str],
    input_paths: List[str],
    generate_subdecks: bool,
    subdecks_exercises: Dict[str, genanki.Deck],
    subdecks_vocab: Dict[str, genanki.Deck],
) -> None:
    """Process input CSV files and add notes to the Anki deck."""
    _ensure_genanki_available()
    _ensure_yaml_available()

    # Create the exercise model here, as there is only one type of model for exercises
    ex_model = _build_exercise_note_model()
    vocab_model_cache: Dict[str, "genanki.Model"] = {}

    # Keep track of if we make new subdecks, and thus need to update the deck_info file
    generated_new_subdecks = False

    for path in input_paths:
        headers, rows = _read_csv(path)

        if _is_exercise(headers):  # Process exercise file
            if not ex_model:
                ex_model = _build_exercise_note_model()
                if not ex_model:
                    raise RuntimeError(
                        "Failed to build exercise model. "
                        "Ensure genanki-model-exercise.yml exists."
                    )

            for row in rows:
                er = _map_exercise_row(row)
                if not er.anki_id:
                    sys.stderr.write(
                        f"Warning: Skipping exercise without Anki_ID: {er.arabic_text[:30]}...\n"
                    )
                    continue

                if generate_subdecks:
                    lesson_string = er.lesson_number or "unknown"

                    # check if a subdeck for this lesson's exercises exists, or if not, create it
                    deck_to_add_note_to, generated_new_subdecks = subdeck_create_or_get(
                        subdecks_exercises,
                        lesson_string,
                        deck.name,
                        "Exercises",
                        generated_new_subdecks,
                    )
                else:  # don't generate subdecks, use main deck
                    deck_to_add_note_to = deck

                # Create the note with GUID from Anki_ID column
                note = genanki.Note(
                    model=ex_model,
                    fields=_exercise_note_fields(er),
                    guid=genanki.guid_for(er.anki_id),
                    tags=[
                        f"lesson:{er.lesson_number}",
                        f"page:{er.page_number}",
                        "type:exercise",
                        f"quran:{er.quran_surah}:{er.quran_ayah}",
                    ],
                )

                # TODO: Optionally attach audio
                # audio_file = download_quran_audio_stub(er.quran_surah, er.quran_ayah)
                # if audio_file:
                #     media.append(audio_file)
                #     # Could modify note fields to include audio tag

                deck_to_add_note_to.add_note(note)

        elif _is_vocab(headers):
            # Process vocabulary file
            for row in rows:
                vr = _map_vocab_row(row)
                if not vr.anki_id:
                    sys.stderr.write(
                        f"Warning: Skipping vocab without Anki_ID: "
                        f"{vr.arabic_word_singular or vr.arabic_word_dual or vr.arabic_word_plural}...\n"
                    )
                    continue

                if generate_subdecks:
                    lesson_string = vr.lesson_number or "unknown"
                    try:
                        lesson_string = int(lesson_string)
                    except (ValueError, TypeError):
                        lesson_string = "unknown"
                        print(
                            "Warning: Non-integer lesson number found, using 'unknown' as lesson string."
                        )

                    # check if a subdeck for this lesson's vocab exists, or if not, create it
                    deck_to_add_note_to, generated_new_subdecks = subdeck_create_or_get(
                        subdecks_vocab,
                        lesson_string,
                        deck.name,
                        "Vocabulary",
                        generated_new_subdecks,
                    )
                else:  # don't generate subdecks, use main deck
                    deck_to_add_note_to = deck

                # Get or create model for this POS
                pos_key = _normalize_pos(vr.part_of_speech)
                if pos_key not in vocab_model_cache:
                    model = _build_vocab_note_model_for(vr.part_of_speech)
                    if not model:
                        raise RuntimeError(
                            f"Failed to build vocab model for POS '{vr.part_of_speech}'. "
                            f"Ensure {_get_vocab_model_filename(pos_key)} exists."
                        )
                    vocab_model_cache[pos_key] = model

                model = vocab_model_cache[pos_key]

                # TODO do we need more conditional card generation logic? https://deepwiki.com/kerrickstaley/genanki/8-advanced-topics#conditional-card-generation
                # Create note with GUID from Anki_ID
                note = genanki.Note(
                    model=model,
                    fields=_vocab_note_fields(vr),
                    # guid=vr.anki_id,
                    guid=genanki.guid_for(vr.anki_id),
                    tags=[
                        f"lesson:{vr.lesson_number}",
                        f"page:{vr.page_number}",
                        f"pos:{_sanitize_tag(vr.part_of_speech) or 'other'}",
                        "type:vocabulary",
                        # "arabic",
                        # "_sanitize_tag(vr.part_of_speech)", #add if blank, no - logic? or jsut 'other'?
                        # "root:{vr.triliteral_root}", # TODO sanitize root?
                        # TODO add other tags? https://deepwiki.com/kerrickstaley/genanki/8-advanced-topics#tag-validation-and-management
                    ],
                )
                deck_to_add_note_to.add_note(note)
        else:
            sys.stderr.write(
                f"Warning: Could not determine CSV type for '{path}'. Skipping.\n"
            )

    if generated_new_subdecks:
        # Write deck_info to yaml file for use in future runs/updating this deck
        print("Updating genanki-deck-info.yml with new subdecks...")
        new_subdecks_list = []

        def _process_subdecks(subdecks_dict, type_str):
            for l_key, s_deck in subdecks_dict.items():
                entry = {
                    "name": s_deck.name,
                    "deck_id": s_deck.deck_id,
                    "type": type_str,
                }
                try:
                    entry["lesson"] = int(l_key)
                except (ValueError, TypeError):
                    pass
                new_subdecks_list.append(entry)

        _process_subdecks(subdecks_vocab, "vocabulary")
        _process_subdecks(subdecks_exercises, "exercises")

        # Sort by lesson then type (vocabulary first)
        new_subdecks_list.sort(
            key=lambda x: (x.get("lesson", 9999), 0 if x["type"] == "vocabulary" else 1)
        )

        new_deck_info = {
            "maindeck": {
                "name": deck.name,
                "deck_id": deck.deck_id,
                "subdecks": new_subdecks_list,
            }
        }

        yaml_header = """# Anki Deck Information for Arabic Through the Qur'an by Alan Jones
# There is one main Anki deck, with a subdeck that contains only the vocabulary
# OR the exercises, for each Lesson. So there are 80 subdecks total. I may
# regret this later.

# This file was mainly created to store the IDs of the decks, so they can be
# recreated by this script and then used to update someone's existing decks.

"""
        from datetime import datetime as dt

        with open("genanki-deck-info.yml", "w") as f:
            f.write(yaml_header)
            f.write(f"# This file created on {dt.now().isoformat()}\n\n")
            yaml.dump(new_deck_info, f, sort_keys=False)


def build_anki_deck(input_paths: List[str], deck_name: str, output_path: str) -> None:
    """Build an Anki deck from input CSV files and save to .apkg file."""

    _ensure_genanki_available()
    _ensure_yaml_available()

    # TODO make deck_info file an input argument. ugh lots of hardcoded things...
    stub_use_yaml_file = True

    # Create empty subdeck lists: one for exercises, one for vocabulary
    subdecks_exercises: Dict[str, genanki.Deck] = {}
    subdecks_vocab: Dict[str, genanki.Deck] = {}

    create_subdecks = True  # TODO make CLI arg
    # TODO modularize this better, how we group entries into subdecks
    subdeck_col_grouping = "lesson"  # what column/key to look at in the input files to decide which subdeck to put a note in

    if stub_use_yaml_file:
        # Load in yaml file with deck (and possibly subdeck) info
        deck_info = _load_yaml_file("genanki-deck-info.yml")

        # Create the main Anki deck with a unique & stable ID
        if "maindeck" in deck_info:
            deck = genanki.Deck(
                deck_id=int(deck_info["maindeck"]["deck_id"]),
                name=deck_info["maindeck"]["name"],
            )
        else:
            print("ERROR: genanki-deck-info.yml missing 'maindeck' section.")
            sys.exit(2)
            # TODO make this better if I use this script for creating any deck other than this specific one

        # TODO also create file to subdeck type mapping (exercise/vocabulary) in this code
        # loop through the list of subdecks in the yaml file and create genanki.Deck objects
        for subdeck in deck_info.get("maindeck", {}).get("subdecks", []):
            if subdeck.get("type") == "exercises":
                subdecks_exercises.update(
                    {
                        subdeck.get(subdeck_col_grouping, "unknown"): genanki.Deck(
                            deck_id=int(subdeck["deck_id"]),
                            name=subdeck["name"],
                        )
                    }
                )
            elif subdeck.get("type") == "vocabulary":
                subdecks_vocab.update(
                    {
                        subdeck.get(subdeck_col_grouping, "unknown"): genanki.Deck(
                            deck_id=int(subdeck["deck_id"]),
                            name=subdeck["name"],
                        )
                    }
                )
            else:
                sys.stderr.write(
                    f"Warning: Unknown subdeck type in genanki-deck-info.yml: {subdeck}\n"
                )
    else:  # no yaml file or existing deck info, make a new top level deck here, then subdecks made in _add_anki_notes
        import random

        # Create the Anki deck. This deck_ID (and those of any created subdecks, if enabled) will be random on the first run,
        #  but are saved to a new genanki-deck-info.yml file for future runs so new deck files can be imported onto existing decks.
        deck = genanki.Deck(
            deck_id=random.randrange(1 << 30, 1 << 31),
            name=deck_name,
        )

    media: List[str] = []
    _add_anki_notes(
        deck, media, input_paths, create_subdecks, subdecks_exercises, subdecks_vocab
    )

    subdeck_list = []
    for lesson_key, sd in subdecks_vocab.items():
        subdeck_list.append(sd)
    for lesson_key, sd in subdecks_exercises.items():
        subdeck_list.append(sd)

    # Create the Anki file/package and write
    pkg = genanki.Package(subdeck_list)
    if media:
        pkg.media_files = media

    pkg.write_to_file(output_path)
    print(f"Wrote Anki deck: {output_path}\n")
    # TODO can this deck be tested without fully launching Anki? See: https://faqs.ankiweb.net/running-from-python.html


# ----------------------------
# Simple CSV output
# ----------------------------


def build_two_column_csv(input_paths: List[str], output_path: str) -> None:
    """
    Emit a simple two-column CSV: Front,Back.
    - Exercises: Front=Arabic Text, Back=English Text (fallback to Transliteration if English missing).
    - Vocabulary: For each row, prefer Singular front; else Dual; else Plural. Back=English Translations.
    """
    out_rows: List[Tuple[str, str]] = []

    for path in input_paths:
        headers, rows = _read_csv(path)

        if _is_exercise(headers):
            for r in rows:
                er = _map_exercise_row(r)
                front = er.arabic_text or er.transliteration
                back = er.english_text or er.transliteration or ""
                if front:
                    # Include Quran reference in back if available
                    if er.quran_surah and er.quran_ayah:
                        back = (
                            f"{back} (Quran {er.quran_surah}:{er.quran_ayah})".strip()
                        )
                    out_rows.append((front, back))

        elif _is_vocab(headers):
            for r in rows:
                vr = _map_vocab_row(r)
                front = (
                    vr.arabic_word_singular
                    or vr.arabic_word_dual
                    or vr.arabic_word_plural
                )
                back = vr.english_translation
                if front and back:
                    out_rows.append((front, back))
        else:
            sys.stderr.write(
                f"Warning: Could not determine CSV type for '{path}'. Skipping.\n"
            )

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Front", "Back"])
        for front, back in out_rows:
            writer.writerow([front, back])

    sys.stdout.write(f"Wrote CSV file: {output_path} ({len(out_rows)} cards)\n")


# ----------------------------
# JSON input (stub)
# ----------------------------


def process_json_input(path: str) -> Tuple[List[ExerciseRow], List[VocabRow]]:
    """
    TODO: Implement JSON input processing.

    Stub function - JSON inputs are accepted but not processed yet.

    Expected to return:
    - List of ExerciseRow objects
    - List of VocabRow objects

    JSON structure should match the CSV columns or a documented schema.
    """
    sys.stderr.write(f"NOTE: JSON input processing not implemented yet: {path}\n")
    return [], []


# ----------------------------
# CLI
# ----------------------------


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    """Parse command line arguments."""
    p = argparse.ArgumentParser(
        description="Create flashcards from Jones Arabic textbook CSVs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create Anki deck from both CSV files (default)
  %(prog)s textbook-jones-exercises.csv textbook-jones-vocabulary.csv

  # Create simple CSV for import to flashcard apps
  %(prog)s --format two_col_csv textbook-jones-vocabulary.csv -o vocab.csv

  # Specify custom deck name and output
  %(prog)s --deck-name "My Arabic Deck" -o my-deck.apkg *.csv
""",
    )
    p.add_argument(
        "inputs",
        nargs="+",
        help="One or more input files (CSV or JSON). Functions to read JSON inputs are stubbed - not implemented yet.",
    )
    p.add_argument(
        "--format",
        choices=["anki", "two_col_csv"],
        default="anki",
        help="Output format: 'anki' (default) for .apkg, 'two_col_csv' for simple two-column CSV",
    )
    p.add_argument(
        "--deck-name",
        default="Arabic Through the Qur'an – Jones",
        help="Anki deck name (only used with anki format)",
    )
    p.add_argument(
        "--output",
        "-o",
        default=None,
        help="Output file path (.apkg for anki, .csv for two_col_csv). Defaults to jones-deck.apkg or jones-cards.csv",
    )
    return p.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    """Main entry point."""
    args = parse_args(argv)

    # Validate inputs and separate CSV from JSON
    csv_inputs: List[str] = []
    json_inputs: List[str] = []

    for path in args.inputs:
        if not os.path.exists(path):
            sys.stderr.write(f"ERROR: input file not found: {path}\n")
            return 2

        if path.lower().endswith(".json"):
            json_inputs.append(path)
        elif path.lower().endswith(".csv"):
            csv_inputs.append(path)
        else:
            sys.stderr.write(f"Warning: Unknown file type, treating as CSV: {path}\n")
            csv_inputs.append(path)

    # Warn about JSON inputs (stubbed)
    for json_path in json_inputs:
        sys.stderr.write(
            f"NOTE: JSON inputs are not implemented yet and will be ignored: {json_path}\n"
        )

    if not csv_inputs:
        sys.stderr.write("ERROR: no usable CSV inputs provided.\n")
        return 2

    # Set default output path if not specified
    if not args.output:
        args.output = "jones-deck.apkg" if args.format == "anki" else "jones-cards.csv"

    # Build output
    if args.format == "anki":
        build_anki_deck(csv_inputs, deck_name=args.deck_name, output_path=args.output)
    else:
        build_two_column_csv(csv_inputs, output_path=args.output)

    # TODO update repo readme with usage instructions and file descriptions

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
